version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: hospital_postgres
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5544:5432"  # Host:21500 -> Container:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: